### ISSUE TITLE
Desconto não é aplicado ao pedido

### ISSUE THREAD

**Issue by zpvini** [vindi/vindi-magento#110]
**Descreva o bug**
Ao finalizar um pedido de pagamento único (não assinatura) o desconto não é contabilizado.

**Como reproduzir**
Passos para reprodução do comportamento:
1. Adicione um cupom de desconto no carrinho
2. Finalize o pedido com a forma de pagamento Vindi - Boleto
3. Compare os valores do painel no admin do magento e no boleto, o valor do boleto não possui o desconto oferecido no Magento

**Comportamento Esperado**
Os descontos devem ser subtraídos do total do pedido.

**Prints de tela**
Magento:
![painel_magento](https://user-images.githubusercontent.com/9328453/57327138-85bb2680-70e4-11e9-972e-b64ec352db17.png)
Vindi:
![painel_vindi](https://user-images.githubusercontent.com/9328453/57327126-7fc54580-70e4-11e9-97d7-124c7f19003a.png)

**Desktop (favor completar as seguintes  informações):**
 - Magento 1.9.3
 - PHP 7.1

**Contexto adicional**
Módulo Vindi_Subscription v1.7.0

**Comment by zpvini** [comment]
Outros clientes reportaram que o desconto também não está aplicando em pedidos de cartão de crédito. Favor verificar.

**Comment by laerte-guimaraes** [comment]
@zpvini Tudo bem?
Primeiramente, muito obrigado pelo contato ! :smiley: 

Realizei alguns testes, e aparentemente seu site utiliza **descontos por método de pagamento**, e essa não é uma funcionalidade nativa do módulo.
Atualmente, o módulo Vindi somente suporta o cupom padrão do Magento.
Poderia nos informar qual a extensão utilizada para criar esse comportamento?

**Comment by zpvini** [comment]
@laerte-guimaraes o desconto por método de pagamento é comportamento padrão das regras de carrinho do magento, nenhum módulo extra necessário.

De qualquer modo, nesse pedido que forneci o print o cliente utilizou um cupom de desconto (via código), tanto que borrei o nome do desconto para não divulgar o nome do cupom.

**Comment by laerte-guimaraes** [comment]
@zpvini consegue enviar para nossa equipe de suporte os logs gerados nas requisições API, e um modelo de como foi configurado o desconto, para que possamos simular em nosso ambiente?

Você pode nos enviar essas informações via [Ticket](https://atendimento.vindi.com.br/hc/pt-br/requests/new) :smiley: 
Desde já, agradeço!

**Comment by ZALESCHI** [comment]
Acontece a mesma coisa por aqui, alguns clientes dizem que colocam o cupom de desconto direto no carrinho e ao finalizar o pedido o desconto não é aplicado, @zpvini o desconto também some no painel do magento nos pedidos certo?

**Comment by ZALESCHI** [comment]
@laerte-guimaraes tem alguma informação sobre isto?

**Comment by laerte-guimaraes** [comment]
@ZALESCHI e @zpvini,
Aparentemente o desconto só não é aplicado em compras avulsas, podem validar?

Fiz algumas alterações, e em breve estaremos disponibilizando na versão oficial.

Segue o [link](https://github.com/vindi/vindi-magento/compare/fix/discounts_to_single_payment?expand=1) :hammer_and_wrench:

**Comment by ZALESCHI** [comment]
@laerte-guimaraes  Vou verificar e retorno. Muito obrigado!

**Comment by ZALESCHI** [comment]
@laerte-guimaraes  muitos clientes reclamando sobre isto, porém  compra avulsa que você diz é fora da assinatura correto? são esses clientes mesmo que estão com o problema.

**Comment by ZALESCHI** [comment]
@laerte-guimaraes  Peguei o código informado e não consigo fechar pedido agora, pode ajudar por favor?

**Comment by ZALESCHI** [comment]
Prezados, temos alguma novidade por favor?

**Comment by laerte-guimaraes** [comment]
Em implantação no PR #116

**Comment by laerte-guimaraes** [comment]
Implementado no PR #116
@ZALESCHI e @zpvini conseguem validar?

**Comment by zpvini** [comment]
> Implementado no PR #116
> @ZALESCHI e @zpvini conseguem validar?

Não estou mais no projeto e acredito que o cliente já trocou de forma de pagamento, portanto deixo pro @ZALESCHI .
Abs

**Comment by ChristianKostner** [comment]
Oi Laerte, acabamos de colocar a loja online tambem e estou vendo o mesmo problema: os descontos de compras avulsas não estão sendo aplicados. Vocês resolveram o assunto? Tem previsão?

**Comment by laerte-guimaraes** [comment]
Sem problemas @zpvini, e de qualquer modo, obrigado pela cooperação :smiley: 

@ChristianKostner já está disponível na nossa última versão [1.8.3](https://github.com/vindi/vindi-magento/releases/tag/1.8.3).

Podem validar?

**Comment by ZALESCHI** [comment]
@laerte-guimaraes  e @zpvini  

Não estou mais neste projeto provavelmente outra pessoa irá validar, obrigado

**Comment by laerte-guimaraes** [comment]
Como não obtive retorno estarei encerrando essa Issue. Porém, qualquer dúvida, estamos à disposição! :smiley:
