### ISSUE TITLE
Parcelamento requerido mesmo desativado no Magento

### ISSUE THREAD

**Issue by ZALESCHI** [vindi/vindi-magento#114]
Quando desativamos o parcelamento no admin do Magento 1.9, ao efetuar um processo de compra, na etapa final ao inserir os dados do cartão e finalizar o pedido o numero de parcelas é pedido, mesmo que estando desabilitada esta função.

**Como reproduzir**
Passos para reprodução do comportamento:
1. Vá ao admin do Magento, clique em sistemas configurações -> métodos de pagamento -> em cartao de crédito vindi desabilite o parcelamento.
2. Tente finalizar um pedido 
3. veja o erro

**Comportamento Esperado**
Ao desabilitar o parcelamento o pedido deve ser fechado sem requisitar parcelas a serem selecionadas.
![WhatsApp Image 2019-06-13 at 18 28 43](https://user-images.githubusercontent.com/11997891/60101474-35e6fc00-9732-11e9-802d-7fed3b7c58ed.jpeg)

 - LInux
 - Browser chrome
 - Version Versão 73.0.3683.103 (Versão oficial) 64 bits
 - Ver. 1.9.3.4 Magento
 - PHP 5.6.1

**Comment by laerte-guimaraes** [comment]
Em implantação no PR #115

**Comment by laerte-guimaraes** [comment]
Implementado no PR #115 
@ZALESCHI consegue validar?

**Comment by laerte-guimaraes** [comment]
Como não obtive retorno estarei encerrando essa Issue. Porém, qualquer dúvida, estamos à disposição! :smiley:
