### ISSUE TITLE
Tipos de cartão.

### ISSUE THREAD

**Issue by luizpuretz** [vindi/vindi-magento#131]
**Não exibe os cartões para selecionar**
Após instalar no Magento, colocar a chave da API, conforme é indicado na explicação, fui fazer um teste, porém não mostra os cartões (visa, mastercard etc) para selecionar, logo não consigo concluir o teste.
Alguém já passou por isso no Magento 1.9?

**Comment by laerte-guimaraes** [comment]
Olá @luizpuretz tudo bem?

Você chegou a habilitar os métodos de pagamento nas configurações do Magento (**Sales** -> **Payment Methods**)?

Exemplo:
![payment_methods_magento1](https://user-images.githubusercontent.com/31661772/67690226-4a0a6680-f97b-11e9-81f1-7f93fdf414ae.gif)

Qualquer dúvida, estamos à disposição! :smiley:

**Comment by luizpuretz** [comment]
@laerte-guimaraes Obrigado pela rápida respostas!
Sim.. fiz isso, aparece as opções de pagamento da VINDI corretamente, porém não aparece o "Tipo de Cartão", veja a imagem abaixo:

![image](https://user-images.githubusercontent.com/1273620/67691066-5939e600-f974-11e9-90ab-eed490026053.png)

**Comment by laerte-guimaraes** [comment]
@luizpuretz que pena :fearful: 

Na tela de configuração do módulo é possível visualizar a mensagem "_conectado com sucesso_"?

Exemplo:
![image](https://user-images.githubusercontent.com/31661772/67696618-f6e9e100-f985-11e9-8eaa-2ddef9e5c569.png)

Pode verificar também, se na sua plataforma existe algum método de pagamento **ativo** para **cartão de crédito** com o **código externo**: `credit_card`?

Exemplo:
![image](https://user-images.githubusercontent.com/31661772/67696860-5c3dd200-f986-11e9-9694-846e52ab3160.png)

O(s) gateway(s) desse método de pagamento possui o status **ativo** e existem bandeiras habilitadas?

Exemplo:
![image](https://user-images.githubusercontent.com/31661772/67696972-914a2480-f986-11e9-9f2f-fde7fc8ffb07.png)

##

Se todos os passos possuirem respostas verdadeiras.

Pode nos enviar uma solicitação de suporte pelo link:
https://atendimento.vindi.com.br/hc/pt-br/requests/new

Assim você pode anexar arquivos de _log_, e/ou mais informações sobre seu **merchant** para que possamos prosseguir com o suporte :smiley:

**Comment by luizpuretz** [comment]
alem desse erro, está dando esse:
"Falha ao registrar o usuário. Verifique os dados e tente novamente!"
Sou o desenvolvedor do cliente CPJUR.

**Comment by luizpuretz** [comment]
Bom dia,
retornando apenas para dizer que o erro estava na versão do cURL.
Atualizei para a versão 7.66.0, e deu certo.
Obrigado.
