### ISSUE TITLE
Produtos configuráveis no Magento são enviados em duplicidade

### ISSUE THREAD

**Issue by victorsinged** [vindi/vindi-magento#133]
**Descreva o bug**
Caso o cliente possua um produto configurável (produto de atributos variáveis), o mesmo será enviado a Vindi em duplicidade:

![image](https://user-images.githubusercontent.com/50752933/72344457-07217a80-36b0-11ea-99fd-f6c0b13e5014.png)

Isso gera confusão ao cliente final, pois em sua fatura o produto é apresentado duas vezes.

**Comment by brunoconstantino** [comment]
Olá,

Comecei a utilizar o módulo da Vindi recentemente, e passei pelo mesmo problema.

Consegui corrigir, alterando o arquivo app/code/community/Vindi/Subscription/Helper/Api.php.

https://github.com/vindi/vindi-magento/blob/e13d37e066fa4d3d3cf2db3dbb097b955ab778fd/app/code/community/Vindi/Subscription/Helper/Api.php#L563

Ao invés de utilizar **$order->getItemsCollection()** , mude para **$order->getAllVisibleItems()**.

A diferença é que _getItemsCollection_ mostra o pai e o filho (produto configurável e simples), enquanto _getAllVisibleItems_ existe apenas o pai (produto configurável).

https://techbandhu.wordpress.com/2013/11/29/magento-what-is-the-difference-between-getallvisibleitems-and-getallitems/
