### ISSUE TITLE
recorrencia

### ISSUE THREAD

**Issue by albertobraschi** [vindi/vindi-magento#16]
esse plugin utiliza o recurso de recorrencia do magento?
posso criar um produto com recurring profile, nominal items, e ele reconhece?

**Comment by mmswebinternet** [comment]
Oi Alberto,
Não, o módulo usa uma customização diferente, utilizando um novo tipo de produto (baseado em um produto simple) onde é informado o ID do plano e produto cadastrado na Vindi.
Abraço
