### ISSUE TITLE
Magento 2.2?

### ISSUE THREAD

**Issue by diegofcv** [vindi/vindi-magento#20]
Olá,
Fiz uma instalação limpa do Magento 2.2 para testar a integração, porém não estou conseguindo fazer funcionar. 
Assim, a primeira questão é saber se este módulo funciona (ou se já foi testado) com esta versão. Se negativo, qual a versão mais recente indicada?
Se o problema não for de versão, procedi com a instalação do Magento com sucesso, fiz a instalação do modman, a clonagem do repositório e a habilitação dos symlinks conforme indicado. Porém não consigo visualizar a Configuração do Vindi conforme informado nas instruções. Não aparece o link para o Vindi em Stores > Configuration, tampouco entre os métodos de pagamento. Alguma ideia? Já tentei esvaziar o cache, desligar/religar o symlinks, rodar o cron e chequei as permissões.
Grato,
Diego

**Comment by lyoncesar** [comment]
Boa tarde @diegofcv, tudo bem?
O nosso módulo ainda não tem suporte para o Magento 2, a última versão compatível com ele é a 1.9.x.
Para dúvidas futuras, por favor utilize o nosso canal de suporte, em atendimento.vindi.com.br ou no e-mail atendimento@vindi.com.br. Nesses dois canais o tempo de resposta será menor ;-)

Abs.
