### ISSUE TITLE
Tudo private na classe Vindi_Subscription_Helper_API

### ISSUE THREAD

**Issue by ebanolopes** [vindi/vindi-magento#4]
Olá, sou desenvolvedor Magento e o meu cliente pediu para acrescentar umas modificações no processo de integração com a Vindi. Porém, para não precisar necessariamente modificar o módulo original e poder efetuar atualizações do mesmo no futuro, eu sempre crio um módulo novo que modificar o módulo original com rewrites e outros artifícios do Magento.

Neste processo vi que a classe Vindi_Subscription_Helper_API está com muitos métodos e propriedades "private". Se pudessem alterar tudo para "protected" ajudaria muito eu e outros desenvolvedores. Assim fica blindada a modificação direta das propriedades ou acesso por classes externas, mas as classes que estenderem a original ainda podem acessar.

Ajuda muitíssimo. Se quiserem eu faço o fork, modifico e mando o pull request.

**Comment by asagalo** [comment]
Olá @ebanolopes,

Claro, como você disse que ira ajudar a todos! :) Uma contribuição é sempre bem vinda, fique à vontade para fazer o fork e mandar o PR.

Abraços,

**Comment by ebanolopes** [comment]
@asagalo feito! Veja o pull request: https://github.com/vindi/vindi-magento/pull/5 Valeu!

**Comment by lyoncesar** [comment]
@ebanolopes, obrigado pela ajuda. Os ajustes que você enviou no PR serão mergeados ainda essa semana.
Qualquer coisa me avise.

Abraços.
