### ISSUE TITLE
Subir plugin para o Marketplace

### ISSUE THREAD

**Issue by rtakauti** [vindi/vindi-magento#70]
Marketing issue

Recursos em lista: Por favor, liste os recursos verticalmente com marcadores no cabeçalho "Recursos".
Realce os recursos e links no ícone de marcador. Isso torna a descrição muito mais fácil de seguir. Para fins de formatação, por favor, use apenas o botão 'bullet point' encontrado no editor ao atualizar a descrição. 'bullet points' em outros estilos infelizmente serão rejeitados.

Guias do usuário em inglês: adicione um conjunto de documentação em inglês.

Conformidade com PCI / Informações de segurança: adicione muito mais informações sobre como os dados do cliente são usados ​​e armazenados. Isso é tratado através de popup? Redirecionar Ambos? A tokenização é usada? Algum dado de cliente atravessa o servidor Magento? Existe algum dado armazenado no servidor Magento? Adicione isso em um cabeçalho separado (usando formatação h3), intitulado "Recursos de segurança".

Cabeçalhos: Os títulos devem ser adicionados a cada seção na descrição longa, exceto para o parágrafo de abertura. (Características, Demonstrações, etc.) Torne os cabeçalhos em negrito e use tags HTML H2 ou H3 para que a descrição longa seja mais fácil de seguir. Os títulos devem ser pretos ou laranja apenas. Nenhuma outra cor será aceita.
Comentários adicionais:
********* Adicione um parágrafo introdutório à descrição longa que fornece mais informações básicas sobre o VINDI (a empresa / serviço) para aqueles que não estão familiarizados. Transforme a primeira menção do VINDI em um hiperlink BOLD que leva ao site do VINDI.

******* Adicione um segundo parágrafo à descrição longa (antes da lista de recursos) que descreve a extensão. Deixe claro o que a extensão pode fazer pelo cliente, como a extensão funciona e forneça recursos detalhados para a extensão. Você pode dar exemplos de casos em que a extensão pode ser usada. Deixe o comerciante com uma sólida compreensão de como seu site aparecerá e funcionará se ele comprar sua extensão. *******

******* Em negrito, após o parágrafo de abertura da descrição longa, adicione o seguinte: *****

   Deixe claro que é necessária uma conta separada.
   Especifique se a conta é ou não criada durante a instalação da extensão.
   Se não for criado durante a instalação da extensão, forneça um link para a página de inscrição.
   Indique se há ou não taxas adicionais para o serviço / conta.
   Em caso afirmativo, adicione um link à página de preços.
   Adicione o seguinte título, usando as tags "h3": "Conta e preço"

**Comment by laerte-guimaraes** [comment]
Feito !
